### ISSUE TITLE
Peer-to-peer code review - meeting step by step

### ISSUE THREAD

**Issue by adelphinsucasa** [Feliverse/To-Do-List#9]
Congratulation this is a great Job. However, I can suggest two things:

1.  In the Readme.md file, update the Future Features section. You have as a future feature the live demo, but it is already implemented. You can use another feature or remove the section.
2. When the live demo is running, the button refresh is not working, it looks like it is missing the eventListener to restart a new list.

**Comment by Feliverse** [comment]
Thanks, Delphin, I applied your suggestions
